#!/bin/sh
# - algo

. $LKP_SRC/lib/upload.sh
. $LKP_SRC/lib/unit.sh
. $LKP_SRC/lib/reproduce-log.sh

cd $BENCHMARK_ROOT/openssl || die "no $BENCHMARK_ROOT/openssl"

echo "Running openssl..."
echo "Algorithm: "$algo

LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH
log_cmd ./apps/openssl speed -multi `nproc` -seconds 30 -elapsed $algo 2>&1  

