#!/usr/bin/env ruby

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.dirname(File.realpath($PROGRAM_NAME)))

require "#{LKP_SRC}/lib/log"
require "#{LKP_SRC}/lib/string_ext"

while (line = $stdin.gets)
  line = line.resolve_invalid_bytes
  case line
  when /^Avr:/
	sub_str = line.split("|",2)	
	# compression
    compression_array = sub_str[0].split(/ /)	
	compression_mips = compression_array[compression_array.length()-1]
	puts "Compression.MIPS: #{compression_mips}"	
	# decompression
	decompression_array = sub_str[1].split(/ /)	
	decompression_mips = decompression_array[decompression_array.length()-1]
	puts "Decompression.MIPS: #{decompression_mips}"
  end
end

